### ISSUE TITLE
Error while executing command: null

### ISSUE THREAD

**Issue by krisjenner** [pie-flavor/Stargate-Sponge#1]
Installed V0.1.3 on my Sponge7.1.0 server and get this error when running /stargate reload command. No errors on console also config folder is empty

**Comment by pie-flavor** [comment]
Please send your log via a gist.

**Comment by krisjenner** [comment]
[gist](https://gist.github.com/krisjenner/0c101fe82a4dbbead3ea20cdb06869cb)

**Comment by Wolvan** [comment]
I have the exact same problem. Stargate fails to even properly launch for one reason or another

**Comment by pie-flavor** [comment]
Please send config as well.

**Comment by Wolvan** [comment]
Doesn't even get to the point where it generates a config from the looks of it

**Comment by pie-flavor** [comment]
Aha. Found the problem. One would think that if I took the trouble to modernize the config I might actually bundle the correct config, but one would be wrong.

**Comment by pie-flavor** [comment]
Fixed in 0.1.4.
