### ISSUE TITLE
Right Click opens Sign Editor

### ISSUE THREAD

**Issue by Possemaster** [pie-flavor/Stargate-Sponge#4]
When portal is created, right click on the sign opens the sign editor. It kinda works if you exit and right click again but this is not user friendly.

This happens also if I demote myself in LuckPerms to regular user.

Also left click works too without this issue, So how can I chnage the text to show Left click to use gate?

**Comment by pie-flavor** [comment]
I don't really know what to tell you other than to disable whatever plugin is providing it. What other plugins do to my signs is out of my hands. Left click can't be used because it's what you use to break it.

**Comment by Possemaster** [comment]
No other Plugins installed. Only SpongForge and StarGate.

**Comment by pie-flavor** [comment]
Then what do you mean by sign editor?
